#ifndef ERRORS_H__

#define ERRORS_H__

#define OK 0
#define ERROR 1
#define ERROR_OPEN_FILE 100
#define ERROR_LEN_ARR 101
#define ERROR_IN_NAME_THEATER 102
#define ERROR_IN_NAME_SHOW 103
#define ERROR_START_PRICE 104
#define ERROR_FINISH_PRICE 105
#define ERROR_TYPE_OF_SHOW 106
#define ERROR_IN_COMPOSER 107
#define ERROR_IN_COUNTRY 108
#define ERROR_IN_TYPE_OF_MUSIC 109
#define ERROR_IN_AGE_START 110
#define ERROR_IN_DURATION 111
#define ERROR_PRICE 112
#define ERROR_AGS 113
#define ERROR_MENU 114
#define ERROR_REMOVE_ELEM 115
#define ZERO_ELEMS 116
#define ERROR_ANALIS 117
#define ERROR_MAXI_ELEMS 118

#endif
